### PR TITLE
readme links to the wrong version of example

### PR DESCRIPTION
**Pull request by rayfoss**
Looks like messages was replaced with a todo.

### CODE REVIEW

**Comment by daffl** [comment]
I'm not following. The Readme does show how to create a `/messages` service no (https://github.com/feathersjs/feathers-localstorage/blame/master/README.md#L53)?

**Comment by rayfoss** [comment]
I don't follow either. It seems like the whole point of this is to run this in the browser not the server. To make that happen Id need to boot strap a package loader... hum

"You can run this example with npm start from the cloned repository and going to localhost:3030/messages. You will see the test Message that we created at the end of that file."

**Comment by daffl** [comment]
You can still use it in Node if you give it a fake localstorage (which is what `var storage = require('localstorage-memory')` is doing). Cloning the repository will run a `todo` but the Readme shows a `messages` example.

**Comment by rayfoss** [comment]
meh.

**Comment by rayfoss** [comment]
app.js is really boring... if it were up to me I would spruce it up with a hint of craziness... people using this are probably far down the rabbit hole

**Pull request closed without merging**
